# Generated by Django 3.0.3 on 2020-02-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200211_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_country', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_district', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('third_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefact', models.DateField()),
                ('count', models.IntegerField()),
                ('number_of_lot', models.IntegerField()),
                ('datestart', models.DateField()),
                ('datefinish', models.DateField()),
                ('price_manufact', models.IntegerField()),
                ('price_pharm', models.IntegerField()),
                ('defect', models.BooleanField()),
                ('reason', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_manufact', models.CharField(max_length=30)),
                ('address_of_manufact', models.CharField(max_length=10)),
                ('email_of_manufact', models.CharField(max_length=12)),
                ('year_of_manufact', models.IntegerField()),
                ('id_of_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_medicament', models.CharField(max_length=20)),
                ('comments', models.TextField()),
                ('bar_code', models.ImageField(height_field=100, upload_to='', width_field=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pharma_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_group', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pharmacy', models.IntegerField()),
                ('title_of_pharmacy', models.CharField(max_length=15)),
                ('address_of_pharmacy', models.CharField(max_length=12)),
                ('phone_of_pharmacy', models.CharField(max_length=10)),
                ('id_of_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.District')),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_shape', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='medicament',
            name='id_of_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Pharma_group'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='id_of_manufact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Manufacturer'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='id_of_shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Shape'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_of_pharm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pharmacy'),
        ),
    ]
