# Generated by Django 3.0.3 on 2020-02-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200215_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='id_of_pharm',
            new_name='id_of_pharmacy',
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='price_manufact',
            new_name='price_manufacturer',
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='price_pharm',
            new_name='price_pharmacy',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='address_of_manufact',
            new_name='address_of_manufacturer',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='email_of_manufact',
            new_name='email_of_manufacturer',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='title_of_manufact',
            new_name='title_of_manufacturer',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='year_of_manufact',
            new_name='year_of_manufacturer',
        ),
        migrations.RenameField(
            model_name='medicament',
            old_name='id_of_manufact',
            new_name='id_of_manufacturer',
        ),
        migrations.RenameField(
            model_name='medicament',
            old_name='id_of_group',
            new_name='id_of_pharma_group',
        ),
        migrations.RenameField(
            model_name='pharma_group',
            old_name='title_of_group',
            new_name='title_of_pharma_group',
        ),
    ]
