# Generated by Django 3.0.3 on 2020-02-19 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200216_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='id_of_medicament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Medicament'),
            preserve_default=False,
        ),
    ]
