# Generated by Django 3.0.3 on 2020-02-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_lot_id_of_medicament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='bar_code',
            field=models.ImageField(height_field=100, upload_to='images/', width_field=100),
        ),
    ]
