# Generated by Django 3.0.3 on 2020-02-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200224_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='address_of_manufacturer',
            field=models.CharField(max_length=70),
        ),
    ]
