# Generated by Django 3.0.3 on 2020-02-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200225_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='id_of_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Type'),
            preserve_default=False,
        ),
    ]
