# Generated by Django 3.0.3 on 2020-02-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200225_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='address_of_manufacturer',
            field=models.CharField(max_length=30),
        ),
    ]
