# Generated by Django 3.0.3 on 2020-02-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200225_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicament',
            old_name='id_of_medicament',
            new_name='id_of_name_of_medicament',
        ),
    ]
