# Generated by Django 3.0.3 on 2020-02-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200225_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='reason',
            field=models.TextField(default=None),
        ),
    ]
