# Generated by Django 3.0.3 on 2020-02-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200227_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='title_of_district',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
