# Generated by Django 3.0.3 on 2020-03-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200301_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='bar_code',
            field=models.TextField(),
        ),
    ]
