# Generated by Django 3.0.3 on 2020-03-31 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='reason',
        ),
        migrations.AddField(
            model_name='lot',
            name='if_of_reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Reason'),
            preserve_default=False,
        ),
    ]
