# Generated by Django 3.0.3 on 2020-03-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200331_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='if_of_reason',
            new_name='id_of_reason',
        ),
    ]
