# Generated by Django 3.0.3 on 2020-05-01 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200501_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='id_of_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Employee'),
        ),
    ]
